DotW/DotW/Controllers/BansController.cs
using Contracts.BanContracts.Request;
using Contracts.CommentaryContracts.Request;
using Contracts.ComplaintContracts.Request;
using Services.BanServices;
using Services.CommentaryServices;
using Services.ComplaintServices;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DotW.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BansController : BaseController
    {
        public ActionResult Index()
        {
            var banService = new BanService();

            ViewBag.Posts = banService.SearchBannedPosts(new SearchBannedPostsRequest()).Posts;
            ViewBag.Comments = banService.SearchBannedComments(new SearchBannedCommentsRequest()).Comments;
            ViewBag.Users = banService.SearchBannedUsers(new SearchBannedUsersRequest()).Users;

            return View();
        }

        public ActionResult EnablePost(int id)
        {
            var banService = new BanService();

            var result = banService.EnablePost(new EnablePostRequest { PostId = id });

            return RedirectToAction("Index");
        }

        public ActionResult EnableCommentary(int id)
        {
            var banService = new BanService();

            var result = banService.EnableCommentary(new EnableCommentaryRequest { CommentaryId = id });

            return RedirectToAction("Index");
        }

        public ActionResult EnableUser(int id)
        {
            var banService = new BanService();

            var result = banService.EnableUser(new EnableUserRequest { UserId = id });

            SendAccountEnabledToUser(result.UserName, result.Email);

            return RedirectToAction("Index");
        }

        public ActionResult CommentaryComplaints(int id)
        {
            var commentaryService = new CommentaryService();
            var complaintService = new ComplaintService();

            ViewBag.Comment = commentaryService.GetCommentaryById(new GetCommentaryByIdRequest { Id = id }).Commentary;
            ViewBag.CommentaryComplaints = complaintService.SearchComplaintsByCommentaryId(new SearchComplaintsByCommentaryIdRequest { CommentaryId = id }).Complaints;

            return View();
        }

        #region Private Methods

        private void SendAccountEnabledToUser(string userName, string email)
        {
            System.Net.Mail.MailMessage m = new System.Net.Mail.MailMessage(
                        new System.Net.Mail.MailAddress("no-reply@devsoftheweb.com", "Devs of the Web"),
                        new System.Net.Mail.MailAddress(email));

            m.Subject = "Cuenta habilitada nuevamente.";

            string body = string.Empty;
            using (StreamReader reader = new StreamReader(Server.MapPath("~/Views/EmailTemplate/AccountEnabled.html")))
            {
                body = reader.ReadToEnd();
            }

            body = body.Replace("{UserName}", userName);

            m.Body = body;

            m.IsBodyHtml = true;
            System.Net.Mail.SmtpClient smtp = new System.Net.Mail.SmtpClient("smtp.gmail.com");
            smtp.Port = 587;
            smtp.EnableSsl = true;
            string emailPassword = ConfigurationManager.AppSettings["EmailPassword"];
            smtp.Credentials = new System.Net.NetworkCredential("devsoftheweb@gmail.com", emailPassword);
            smtp.Send(m);
        }

        #endregion
    }
}

DotW/DotW/Controllers/ProfileController.cs
namespace DotW.Controllers
{
    using Contracts.PostContracts.Request;
    using Contracts.UserContracts.Request;
    using Entities.UserEntities;
    using Microsoft.AspNet.Identity;
    using Models;
    using Services.PostServices;
    using Services.UserServices;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web;
    using System.Web.Mvc;

    public class ProfileController : BaseController
    {
        [Authorize]
        public ActionResult Details(int id)
        {
            var userService = new UserService();
            var postService = new PostService();
            var user = userService.GetUserById(new GetUserByIdRequest() { UserId = id }).User;

            if (user != null)
            {
                var posts = postService.SearchPostsByUserId(new SearchPostsByUserIdRequest() { UserId = id }).Posts.Where(x => !x.IsDraft).ToList();

                ViewBag.Posts = posts;

                return View(user);
            }

            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "User")]
        public ActionResult Edit()
        {
            var userService = new UserService();
            var user = userService.GetUserByAccountId(new GetUserByAccountIdRequest() { AccountId = User.Identity.GetUserId() }).User;

            if (user != null)
            {
                var model = new EditProfileViewModel
                {
                    Phone = user.Phone,
                    FullName = user.FullName,
                    Description = user.Description,
                    ShowData = user.ShowData
                };

                return View(model);
            }
            else
            {
                return RedirectToAction("Index", "Manage");
            }
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public ActionResult Edit(EditProfileViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userService = new UserService();
                var user = userService.GetUserByAccountId(new GetUserByAccountIdRequest() { AccountId = User.Identity.GetUserId() }).User;

                if (user != null)
                {
                    var request = new UpdateProfileRequest
                    {
                        Id = user.Id,
                        Description = model.Description,
                        Phone = model.Phone,
                        FullName = model.FullName,
                        ShowData = model.ShowData
                    };

                    var response = userService.UpdateProfile(request);

                    return RedirectToAction("Index", "Manage");
                }
            }

            return View(model);
        }
    }
}

DotW/DotW/Views/Bans/CommentaryComplaints.cshtml
@{
    ViewBag.Title = "Denuncias del comentario";
    var comment = ViewBag.Comment as Entities.CommentaryEntities.Commentary;
    var complaints = ViewBag.CommentaryComplaints as List<Entities.ComplaintEntities.Complaint>;
}

<h3>Comentario</h3>
<p>@comment.CommentaryText</p>
<p>Publicado el @comment.EffectDate.ToString("dd/MM/yyyy") por <a href="@Url.Action("Details", "Profile", new { id = comment.IdUser })" target="_blank">@comment.WriterUserName</a>.</p>
<br />
@Html.ActionLink("Ver publicación donde se encontraba el comentario", "Details", "Post", new { id = comment.IdPost }, new { @class = "btn btn-primary", target = "_blank" })
<br />
<h3 class="text-danger"><b>Denuncias</b></h3>
<ul>
    @foreach (var complaint in complaints)
    {
        <li><a href="@Url.Action("Details", "Profile", new { id = complaint.IdUser })" target="_blank">@complaint.UserName</a>: @complaint.Description</li>
    }
</ul>
<br />
<p>
    @Html.ActionLink("Volver", null, null, null, new { href = Request.UrlReferrer, @class = "btn btn-default" })
    @Html.ActionLink("Habilitar", "EnableCommentary", "Bans", new { id = comment.Id }, new { @class = "btn btn-success" })
</p>

DotW/DotW/Views/Bans/Index.cshtml
@{
    ViewBag.Title = "Bloqueos y Suspensiones";
    var posts = ViewBag.Posts as List<Entities.PostEntities.Post>;
    var comments = ViewBag.Comments as List<Entities.CommentaryEntities.Commentary>;
    var users = ViewBag.Users as List<Entities.UserEntities.User>;
}

<h3>Publicaciones baneadas</h3>
<br />
<table class="table">
    <thead class="thead-inverse">
        <tr>
            <th>Título</th>
            <th>Fecha alta</th>
            <th>Fecha baja</th>
            <th>Autor</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var post in posts)
        {
            <tr>
                <td>@post.Title</td>
                <td>@post.EffectDate.ToString("dd/MM/yyyy")</td>
                <td>@post.NullDate.Value.ToString("dd/MM/yyyy")</td>
                <td>@post.WriterUserName</td>
                <td>
                    @Html.ActionLink("Detalle y denuncias", "Details", "Post", new { id = post.Id }, new { @class = "btn btn-primary", target = "_blank"})
                    @Html.ActionLink("Habilitar", "EnablePost", "Bans", new { id = post.Id }, new { @class = "btn btn-success" })
                </td>
            </tr>
        }
    </tbody>
</table>
<hr />
<h3>Comentarios baneados</h3>
<br />
<table class="table">
    <thead class="thead-inverse">
        <tr>
            <th>Comentario</th>
            <th>Fecha alta</th>
            <th>Fecha baja</th>
            <th>Autor</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var comment in comments)
        {
            <tr>
                <td style="max-width:450px">@comment.CommentaryText</td>
                <td>@comment.EffectDate.ToString("dd/MM/yyyy")</td>
                <td>@comment.NullDate.Value.ToString("dd/MM/yyyy")</td>
                <td>@comment.WriterUserName</td>
                <td>
                    @Html.ActionLink("Detalle y denuncias", "CommentaryComplaints", "Bans", new { id = comment.Id }, new { @class = "btn btn-primary", target = "_blank" })
                    @Html.ActionLink("Habilitar", "EnableCommentary", "Bans", new { id = comment.Id }, new { @class = "btn btn-success" })
                </td>
            </tr>
        }
    </tbody>
</table>
<hr />
<h3>Usuarios baneados</h3>
<br />
<table class="table">
    <thead class="thead-inverse">
        <tr>
            <th>Nombre de Usuario</th>
            <th>Fecha alta</th>
            <th>Fecha reactivación</th>
            <th>Email</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in users)
        {
            <tr>
                <td><a href="@Url.Action("Details", "Profile", new { id = user.Id })" target="_blank">@user.Name</a></td>
                <td>@user.EffectDate.ToString("dd/MM/yyyy")</td>
                <td>@user.ActivationDate.Value.ToString("dd/MM/yyyy HH:mm")</td>
                <td>@user.Email</td>
                <td>
                    @Html.ActionLink("Habilitar", "EnableUser", "Bans", new { id = user.Id }, new { @class = "btn btn-success" })
                </td>
            </tr>
        }
    </tbody>
</table>