DotW/DotW/Controllers/ProfileController.cs
namespace DotW.Controllers
{
    using Contracts.PostContracts.Request;
    using Contracts.UserContracts.Request;
    using Entities.UserEntities;
    using Microsoft.AspNet.Identity;
    using Models;
    using Services.PostServices;
    using Services.UserServices;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web;
    using System.Web.Mvc;

    public class ProfileController : BaseController
    {
        [Authorize]
        public ActionResult Details(int id)
        {
            var userService = new UserService();
            var postService = new PostService();
            var user = userService.GetUserById(new GetUserByIdRequest() { UserId = id }).User;

            if (user != null)
            {
                var posts = postService.SearchPostsByUserId(new SearchPostsByUserIdRequest() { UserId = id }).Posts.Where(x => !x.IsDraft).ToList();

                ViewBag.Posts = posts;

                return View(user);
            }

            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "User")]
        public ActionResult Edit()
        {
            var userService = new UserService();
            var user = userService.GetUserByAccountId(new GetUserByAccountIdRequest() { AccountId = User.Identity.GetUserId() }).User;

            if (user != null)
            {
                var model = new EditProfileViewModel
                {
                    Phone = user.Phone,
                    FullName = user.FullName,
                    Description = user.Description,
                    ShowData = user.ShowData
                };

                return View(model);
            }
            else
            {
                return RedirectToAction("Index", "Manage");
            }
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public ActionResult Edit(EditProfileViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userService = new UserService();
                var user = userService.GetUserByAccountId(new GetUserByAccountIdRequest() { AccountId = User.Identity.GetUserId() }).User;

                if (user != null)
                {
                    var request = new UpdateProfileRequest
                    {
                        Id = user.Id,
                        Description = model.Description,
                        Phone = model.Phone,
                        FullName = model.FullName,
                        ShowData = model.ShowData
                    };

                    var response = userService.UpdateProfile(request);

                    return RedirectToAction("Index", "Manage");
                }
            }

            return View(model);
        }
    }
}

DotW/DotW/Controllers/SearchController.cs
using Contracts.SearchContracts.Request;
using Entities.SearchEntities;
using Services.SearchServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DotW.Controllers
{
    public class SearchController : BaseController
    {
        public ActionResult Index(string text)
        {
            var searchService = new SearchService();

            ViewBag.PostsList = searchService.SearchInPosts(new SearchInPostsRequest { Text = text }).PostsSearchResult;

            ViewBag.CommentsList = searchService.SearchInComments(new SearchInCommentsRequest { Text = text }).CommentsSearchResult;

            return View();
        }

        public ActionResult Terms()
        {
            return View();
        }
    }
}

DotW/DotW/Views/Search/Index.cshtml
@{
    ViewBag.Title = "Resultados de Búsqueda";
    var postsList = ViewBag.PostsList as List<Entities.SearchEntities.PostsSearchResult>;
    var commentsList = ViewBag.CommentsList as List<Entities.SearchEntities.CommentsSearchResult>;
}

<div class="container">
    <div class="row">
        <div class="col-lg-8">
            @if (postsList.Any())
            {
                <h4>Publicaciones que coinciden con su criterio de búsqueda.</h4>
                foreach (var post in postsList)
                {
                    <h4><a href="@Url.Action("Details", "Post", new { id = post.Id })">@post.Title</a></h4>
                    <p><span class="glyphicon glyphicon-time"></span> Publicado el @post.EffectDate.ToString("dd/MM/yyyy") por <a href="@Url.Action("Details", "Profile", new { id = post.IdWriter })" target="_blank">@post.WriterUserName</a></p>
                    <p class="post-summary">@post.Summary</p>
                    <hr />
                }
            }
            else
            {
                <h4>No se han encontrado resultados <b>dentro de las publicaciones</b>. Intente con una búsqueda diferente.</h4>
                <br />
            }

            @if (commentsList.Any())
            {
                <hr />
                <h4>Comentarios que coinciden con su criterio de búsqueda.</h4>
                <br />
                foreach (var commentary in commentsList)
                {
                    <div class="media" id="@commentary.Id">
                        <a class="pull-left" href="#" onclick="return false;">
                            <img class="media-object" src="~/Content/Images/GenericUser.png" height="64" width="64">
                        </a>
                        <div class="media-body">
                            <h4 class="media-heading">
                                <a href="@Url.Action("Details", "Profile", new { id = commentary.IdUser })" target="_blank">@commentary.WriterUserName</a>
                            </h4>
                            <a href="/Post/Details/@(commentary.IdPost)#@commentary.Id">@commentary.Commentary</a>
                        </div>
                    </div>
                }
                <br />
            }
            else
            {
                <h4>No se han encontrado resultados <b>dentro de los comentarios</b>. Intente con una búsqueda diferente.</h4>
            }
        </div>
        <div class="col-md-4">
            <div class="well">
                <div class="row">
                    <div class="col-lg-12">
                        <h4>Búsqueda</h4>
                        <ul class="list-unstyled">
                            <li>@Html.ActionLink("Términos de búsqueda", "Terms", "Search")</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br />
<div class="col-md-2">
    <p>
        @Html.ActionLink("Volver", null, null, null, new { href = Request.UrlReferrer, @class = "btn btn-default" })
    </p>
</div>

DotW/DotW/Views/Search/Terms.cshtml
@{
    ViewBag.Title = "Criterios de búsqueda";
}

<h3>¿Cómo se realizan las búsquedas dentro de Devs of the Web?</h3>
<br />
<h4>Dentro de las publicaciones se busca en:</h4>
<ul>
    <li>Título.</li>
    <li>Resumen.</li>
    <li>Nombre de usuario del autor.</li>
    <li>Cuerpo de la publicación.</li>
</ul>
<br />
<h4>Dentro de los comentarios se busca en:</h4>
<ul>
    <li>Cuerpo del comentario.</li>
</ul>
<br />
<br />

<div class="col-md-2">
    <p>
        @Html.ActionLink("Volver", null, null, null, new { href = Request.UrlReferrer, @class = "btn btn-default" })
    </p>
</div>