DotW/DotW/Models/ComplaintViewModel.cs
namespace DotW.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;

    public class PostComplaintViewModel
    {
        [Required(ErrorMessage = "El campo Comentario es obligatorio")]
        [Display(Name = "Comentario")]
        public string Commentary { get; set; }

        [Required]
        public int PostId { get; set; }
    }

    public class CommentaryComplaintViewModel
    {
        [Required(ErrorMessage = "El campo Comentario es obligatorio")]
        [Display(Name = "Comentario")]
        public string Commentary { get; set; }

        [Required]
        public int CommentaryId { get; set; }
    }
}

DotW/DotW/Models/PostViewModel.cs
using Entities.PostEntities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DotW.Models
{
    public class CreatePostViewModel
    {
        [Required(ErrorMessage = "El campo Título es requerido.")]
        [Display(Name = "Título")]
        public string Title { get; set; }

        public HttpPostedFileBase File { get; set; }

        [Display(Name = "Imagen principal")]
        public string ImageName { get; set; }

        [Required(ErrorMessage = "El campo Escritor es requerido.")]
        [Display(Name = "Escritor")]
        public int IdWriter { get; set; }

        [Required(ErrorMessage = "El campo Resumen es requerido.")]
        [MaxLength(500, ErrorMessage = "El Resumen debe tener como máximo una longitud de 500 caracteres.")]
        [Display(Name = "Resumen")]
        public string Summary { get; set; }

        [Required(ErrorMessage = "El campo Cuerpo es requerido.")]
        [Display(Name = "Cuerpo")]
        public string Body { get; set; }

        [Required(ErrorMessage = "La Categoría es requerida.")]
        [Display(Name = "Categoría")]
        public int IdCategory { get; set; }

        [Display(Name = "Es borrador")]
        public bool IsDraft { get; set; }

        [Display(Name = "Tags")]
        public List<string> Tags { get; set; }

        public CreatePostViewModel()
        {
            Tags = new List<string>();
        }
    }

    public class EditPostViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "El campo Título es requerido.")]
        [Display(Name = "Título")]
        public string Title { get; set; }

        public HttpPostedFileBase File { get; set; }

        [Display(Name = "Imagen principal")]
        public string ImageName { get; set; }

        [Display(Name = "Imagen cargada")]
        public string PrincipalImageName { get; set; }

        [Required(ErrorMessage = "El campo Resumen es requerido.")]
        [MaxLength(500, ErrorMessage = "El Resumen debe tener como máximo una longitud de 500 caracteres.")]
        [Display(Name = "Resumen")]
        public string Summary { get; set; }

        [Required(ErrorMessage = "El campo Cuerpo es requerido.")]
        [Display(Name = "Cuerpo")]
        public string Body { get; set; }

        [Required(ErrorMessage = "La Categoría es requerida.")]
        [Display(Name = "Categoría")]
        public int IdCategory { get; set; }

        [Display(Name = "Es borrador")]
        public bool IsDraft { get; set; }

        [Display(Name = "Tags")]
        public List<string> Tags { get; set; }

        [Display(Name = "Publicación sin imagen")]
        public bool DeleteImage { get; set; }

        public EditPostViewModel()
        {
            Tags = new List<string>();
        }
    }

    public class DeletePostViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Título")]
        public string Title { get; set; }

        [Display(Name = "Resumen")]
        public string Summary { get; set; }

        [Display(Name = "Categoría")]
        public string CategoryTitle { get; set; }

        [Display(Name = "Estado")]
        public bool IsDraft { get; set; }

        [Display(Name = "Tags")]
        public List<string> Tags { get; set; }
    }

    public class IndexPostViewModel
    {
        public List<Post> Posts { get; set; }
    }

    public class ListPostViewModel
    {
        public List<Post> Posts { get; set; }
    }
}

DotW/DotW/Controllers/ComplaintController.cs
namespace DotW.Controllers
{
    using Contracts.CommentaryContracts.Request;
    using Contracts.ComplaintContracts;
    using Contracts.ComplaintContracts.Request;
    using Contracts.PostContracts.Request;
    using Contracts.UserContracts.Request;
    using DotW.Models;
    using Entities.CommentaryEntities;
    using Entities.ComplaintEntities;
    using Entities.PostEntities;
    using Microsoft.AspNet.Identity;
    using Services.CommentaryServices;
    using Services.ComplaintServices;
    using Services.PostServices;
    using Services.UserServices;
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.IO;
    using System.Linq;
    using System.Web.Mvc;

    public class ComplaintController : BaseController
    {
        [Authorize(Roles = "User")]
        [HttpPost]
        public JsonResult PostComplaint(PostComplaintViewModel model)
        {
            var complaintService = new ComplaintService();
            var userService = new UserService();
            var postService = new PostService();

            try
            {
                var user = userService.GetUserByAccountId(new GetUserByAccountIdRequest { AccountId = User.Identity.GetUserId() }).User;

                if (user != null)
                {
                    var userComplaints = complaintService.SearchComplaintsByUserId(new SearchComplaintsByUserIdRequest { UserId = user.Id }).Complaints;

                    if (userComplaints.Any(x => x.IdPost == model.PostId))
                    {
                        return Json(new { success = false, Message = "Ya se ha registrado una denuncia para esta cuenta en esta publicación." }, JsonRequestBehavior.AllowGet);
                    }

                    var post = postService.GetPostById(new GetPostByIdRequest { Id = model.PostId }).Post;

                    if (post.IdWriter == user.Id)
                    {
                        return Json(new { success = false, Message = "No puede denunciar su propia publicación." }, JsonRequestBehavior.AllowGet);
                    }

                    var complaintResult = complaintService.CreatePostComplaint(new CreatePostComplaintRequest { PostId = model.PostId, UserId = user.Id, Commentary = model.Commentary });

                    if ((complaintResult.PostComplaintsCount % (int)DividersToDeleteByComplaint.PostAndCommentaryDeletedDivider) == 0)
                    {
                        // Se da de baja la publicación.
                        var deletePostResult = postService.DeletePost(new DeletePostRequest { Id = complaintResult.PostId, IsComplaintOrVoteDifference = true });

                        var complaints = complaintService.SearchComplaintsByPostId(new SearchComplaintsByPostIdRequest { PostId = post.Id }).Complaints.OrderByDescending(x => x.Id).Take(3).ToList();

                        // Se notifica la baja del post via correo electrónico al escritor.
                        SendPostDeletedEmailToWriter(post, complaints);

                        // Se verifica y de ser necesario, se suspende temporalmente la cuenta del usuario.
                        var verifyResult = userService.VerifyAndUpdateUserStateByPosts(new VerifyAndUpdateUserStateByPostsRequest { UserId = post.IdWriter });

                        if (verifyResult.UserSuspended)
                        {
                            var reason = "La cantidad de publicaciones dadas de baja por denuncias ha alcanzando el número estipulado para suspender temporalmente su cuenta.";
                            SendAccountBlockedToWriter(post.IdWriter, verifyResult.ActivationDate, reason);
                        };
                    }

                    return Json(new { success = true, Message = "<div style='text-align:justify;'>Su denuncia ha sido registrada y será colocada junto a la de otros usuarios. Si se alcanza el límite establecido en nuestros <a href='/Home/TermsAndConditions' target='_blank'>Términos y Condiciones</a>, la publicación será dada de baja.<br><br>Gracias por contribuir con nuestra comunidad :)</div>" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, Message = "Ha ocurrido un error al procesar la solicitud." }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception e)
            {
                return Json(new { success = false, Message = "Ha ocurrido un error al procesar la solicitud." }, JsonRequestBehavior.AllowGet);
            }
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public JsonResult CommentaryComplaint(CommentaryComplaintViewModel model)
        {
            var commentaryService = new CommentaryService();
            var complaintService = new ComplaintService();
            var userService = new UserService();

            try
            {
                var user = userService.GetUserByAccountId(new GetUserByAccountIdRequest { AccountId = User.Identity.GetUserId() }).User;

                if (user != null)
                {
                    var userComplaints = complaintService.SearchComplaintsByUserId(new SearchComplaintsByUserIdRequest { UserId = user.Id }).Complaints;

                    if (userComplaints.Any(x => x.IdComment == model.CommentaryId))
                    {
                        return Json(new { success = false, Message = "Ya se ha registrado una denuncia para esta cuenta en este comentario." }, JsonRequestBehavior.AllowGet);
                    }

                    var commentary = commentaryService.GetCommentaryById(new GetCommentaryByIdRequest { Id = model.CommentaryId }).Commentary;

                    if (commentary.IdUser == user.Id)
                    {
                        return Json(new { success = false, Message = "No puede denunciar su propio comentario." }, JsonRequestBehavior.AllowGet);
                    }

                    var complaintResult = complaintService.CreateCommentaryComplaint(new CreateCommentaryComplaintRequest { CommentaryId = model.CommentaryId, UserId = user.Id, Commentary = model.Commentary });

                    if ((complaintResult.CommentaryComplaintsCount % (int)DividersToDeleteByComplaint.PostAndCommentaryDeletedDivider) == 0)
                    {                       
                        // Se da de baja el comentario.
                        var deletePostResult = commentaryService.DeleteCommentary(new DeleteCommentaryRequest { Id = complaintResult.CommentaryId, IsComplaintOrVoteDifference = true });

                        var complaints = complaintService.SearchComplaintsByCommentaryId(new SearchComplaintsByCommentaryIdRequest { CommentaryId = commentary.Id }).Complaints.OrderByDescending(x => x.Id).Take(3).ToList();

                        // Se notifica la baja del comentario via correo electrónico al escritor.
                        SendCommentaryDeletedEmailToWriter(commentary, complaints);

                        // Se verifica y de ser necesario, se suspende temporalmente la cuenta del usuario.
                        var verifyResult = userService.VerifyAndUpdateUserStateByComments(new VerifyAndUpdateUserStateByCommentsRequest { UserId = commentary.IdUser });

                        if (verifyResult.UserSuspended)
                        {
                            var reason = "La cantidad de comentarios dados de baja por denuncias ha alcanzando el número estipulado para suspender temporalmente su cuenta.";
                            SendAccountBlockedToWriter(commentary.IdUser, verifyResult.ActivationDate, reason);
                        };
                    }

                    return Json(new { success = true, Message = "<div style='text-align:justify;'>Su denuncia ha sido registrada y será colocada junto a la de otros usuarios. Si se alcanza el límite establecido en nuestros <a href='/Home/TermsAndConditions' target='_blank'>Términos y Condiciones</a>, el comentario será dado de baja.<br><br>Gracias por contribuir con nuestra comunidad :)</div>" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, Message = "Ha ocurrido un error al procesar la solicitud." }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception e)
            {
                return Json(new { success = false, Message = "Ha ocurrido un error al procesar la solicitud." }, JsonRequestBehavior.AllowGet);
            }
        }

        #region Private Methods

        private void SendPostDeletedEmailToWriter(Post post, IList<Complaint> complaints)
        {
            var userService = new UserService();

            var writerUser = userService.GetUserById(new GetUserByIdRequest { UserId = post.IdWriter }).User;

            if (writerUser != null)
            {
                System.Net.Mail.MailMessage m = new System.Net.Mail.MailMessage(
                        new System.Net.Mail.MailAddress("no-reply@devsoftheweb.com", "Devs of the Web"),
                        new System.Net.Mail.MailAddress(writerUser.Email));

                m.Subject = "Publicación eliminada por denuncias.";

                string body = string.Empty;
                using (StreamReader reader = new StreamReader(Server.MapPath("~/Views/EmailTemplate/PostDeletedByComplaints.html")))
                {
                    body = reader.ReadToEnd();
                }

                body = body.Replace("{UserName}", writerUser.Name);
                body = body.Replace("{PostTitle}", post.Title);
                body = body.Replace("{FirstComplaint}", string.IsNullOrEmpty(complaints[0].Description) ? "Denuncia sin comentario." : complaints[0].Description);

DotW/DotW/Controllers/ProfileController.cs
namespace DotW.Controllers
{
    using Contracts.PostContracts.Request;
    using Contracts.UserContracts.Request;
    using Entities.UserEntities;
    using Microsoft.AspNet.Identity;
    using Models;
    using Services.PostServices;
    using Services.UserServices;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web;
    using System.Web.Mvc;

    public class ProfileController : BaseController
    {
        [Authorize]
        public ActionResult Details(int id)
        {
            var userService = new UserService();
            var postService = new PostService();
            var user = userService.GetUserById(new GetUserByIdRequest() { UserId = id }).User;

            if (user != null)
            {
                var posts = postService.SearchPostsByUserId(new SearchPostsByUserIdRequest() { UserId = id }).Posts.Where(x => !x.IsDraft).ToList();

                ViewBag.Posts = posts;

                return View(user);
            }

            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "User")]
        public ActionResult Edit()
        {
            var userService = new UserService();
            var user = userService.GetUserByAccountId(new GetUserByAccountIdRequest() { AccountId = User.Identity.GetUserId() }).User;

            if (user != null)
            {
                var model = new EditProfileViewModel
                {
                    Phone = user.Phone,
                    FullName = user.FullName,
                    Description = user.Description,
                    ShowData = user.ShowData
                };

                return View(model);
            }
            else
            {
                return RedirectToAction("Index", "Manage");
            }
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public ActionResult Edit(EditProfileViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userService = new UserService();
                var user = userService.GetUserByAccountId(new GetUserByAccountIdRequest() { AccountId = User.Identity.GetUserId() }).User;

                if (user != null)
                {
                    var request = new UpdateProfileRequest
                    {
                        Id = user.Id,
                        Description = model.Description,
                        Phone = model.Phone,
                        FullName = model.FullName,
                        ShowData = model.ShowData
                    };

                    var response = userService.UpdateProfile(request);

                    return RedirectToAction("Index", "Manage");
                }
            }

            return View(model);
        }
    }
}

DotW/DotW/Views/Post/Create.cshtml
@model DotW.Models.CreatePostViewModel
@{
    ViewBag.Title = "Nueva publicación";
}

@section Styles {
    <link href="~/Content/ckeditor/ckeditor_style.css" rel="stylesheet" />
    <link href="~/Content/tagsinput/src/bootstrap-tagsinput.css" rel="stylesheet" />
}

<h2>Crear una nueva publicación</h2>

@using (Html.BeginForm("Create", "Post", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ImageName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10 input-group">
            <label class="input-group-btn">
                <span class="btn btn-primary">
                    Examinar… <input id="imageInput" type="file" name="File" accept="image/*" />
                </span>
            </label>
            <input id="imageNameField" type="text" class="form-control" readonly="">
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Summary, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Summary, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Body, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Body, new { @id = "postEditor", @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">Tags</label>
        <div class="col-md-10">
            @if (Model != null)
            {
                <input type="text" id="postTags" value="@string.Join(",", Model.Tags)" data-role="tagsinput" />
                foreach (var tag in Model.Tags)
                {
                    <input id="@tag" name="Tags" type="hidden" value="@tag" />;
                }
            }
            else
            {
                <input type="text" id="postTags" data-role="tagsinput" />
            }
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.IdCategory, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.IdCategory, (IEnumerable<SelectListItem>)ViewBag.Categories, "Seleccione una categoría", new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.IsDraft, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.IsDraft)
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-success" value="Publicar" />
        </div>
    </div>
    <p>
        @Html.ActionLink("Listado de mis publicaciones", "Index", "Post", null, new { @class = "btn btn-default" })
    </p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript" src="~/Content/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="~/Scripts/Post/ckeditor.js"></script>
    <script type="text/javascript" src="~/Scripts/Post/Create.js"></script>
    <script type="text/javascript" src="~/Content/tagsinput/src/bootstrap-tagsinput.js"></script>
}

DotW/DotW/Views/Post/List.cshtml
@using System.Configuration;

@model DotW.Models.ListPostViewModel
@{
    ViewBag.Title = "Publicaciones";
    List<Entities.CategoryEntities.Category> categories = ViewBag.Categories as List<Entities.CategoryEntities.Category>;
}

@section Styles {
    <script type="text/javascript" src="~/Content/ckeditor/ckeditor.js"></script>
    <link href="~/Content/ckeditor/ckeditor_style.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/Content/blog-post.css" rel="stylesheet">
    <!-- Code Highlight -->
    <link href="~/Content/ckeditor/plugins/codesnippet/lib/highlight/styles/monokai_sublime.css" rel="stylesheet" />
}

<div class="container">
    <div class="row">
        <!-- Blog Post Content Column -->
        <div class="col-lg-8">
            @if (Model.Posts.Any())
            {
                foreach (var post in Model.Posts)
                {
                    <h4><a href="@Url.Action("Details", "Post", new { id = post.Id })">@post.Title</a></h4>
                    <p><span class="glyphicon glyphicon-time"></span> Publicado el @post.EffectDate.ToString("dd/MM/yyyy") por <a href="@Url.Action("Details", "Profile", new { id = post.IdWriter })">@post.WriterUserName</a></p>
                    <!-- Preview Image -->
                    if (!string.IsNullOrEmpty(post.PrincipalImageName))
                    {
                        if (post.PrincipalImageName.Contains("api/"))
                        {
                            <a href="@Url.Action("Details", "Post", new { id = post.Id })"><img class="img-responsive" src="@Url.Content((ConfigurationManager.AppSettings["UrlImagesAPI"]) + post.PrincipalImageName.Split('/')[1])" alt=""></a>
                        }
                        else
                        {
                            <a href="@Url.Action("Details", "Post", new { id = post.Id })"><img class="img-responsive" src="@Url.Content((ConfigurationManager.AppSettings["PathPostPrincipalImages"]) + post.PrincipalImageName)" alt=""></a>
                        }
                    }
                    <br />
                    <p class="post-summary">@post.Summary</p>
                    foreach (var tag in post.Tags)
                    {
                        <a href="@Url.Action("List", "Post", new { tag = tag })" class="tag-link"><span class="tag label label-info">@tag</span></a>
                    }
                    <hr />
                }
            }
            else
            {
                <h1>No hay publicaciones asociadas a esta categoría.</h1>
            }
        </div>
        <div class="col-md-4">
            <div class="well">
                <div class="row">
                    <div class="col-lg-6">
                        <h4>Categorías</h4>
                        <ul class="list-unstyled">
                            @foreach (var category in categories.OrderBy(x => x.Title))
                            {
                                <li>@Html.ActionLink(category.Title, "List", "Post", new { idCategory = category.Id }, null)</li>
                            }
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            <li>@Html.ActionLink("Ver todas", "List", null, new { @class = "btn btn-success" })</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="well">
                <div class="row">
                    <div class="col-lg-12">
                        <h5>Reglas del sitio</h5>
                        <ul class="list-unstyled">
                            <li>@Html.ActionLink("Términos y Condiciones", "TermsAndConditions", "Home")</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <!-- View JavaScript -->
    <script src="~/Scripts/Post/List.js"></script>
    <!-- Code Highlight -->
    <script src="~/Content/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js"></script>
}

DotW/DotW/Views/Post/_CommentaryComplaint.cshtml
@model DotW.Models.CommentaryComplaintViewModel

<div id="commentaryComplaintModal" class="modal fade in" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content row">
            <div class="modal-header custom-modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 class="modal-title">Denunciar Comentario</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("CommentaryComplaint", "Complaint", FormMethod.Post, new { @id = "commentaryComplaintForm", @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group" id="commentaryComplaintComment">
                        @Html.LabelFor(model => model.Commentary, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Commentary, new { @id = "commentaryComplaintTextArea", @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group" id="commentaryComplaintResult" style="display: none;">
                        <div class="col-md-12">
                            <p id="commentaryComplaintResultText"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            @Html.HiddenFor(model => model.CommentaryId, new { @id = "commentaryIdFormField" })
                            <input type="submit" id="commentaryComplaintSubmit" class="btn btn-success" value="Denunciar" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.ActionLink("Listado de Publicaciones", "List", "Post", null, new { @id = "commentaryGoBackBtn", @class = "btn btn-success", @style = "display: none;" })
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

DotW/DotW/Views/Post/_Complaint.cshtml
@model DotW.Models.ComplaintPostViewModel

<div id="denouncementModal" class="modal fade in" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content row">
            <div class="modal-header custom-modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 class="modal-title">Denunciar Publicación</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("PostComplaint", "Complaint", FormMethod.Post, new { @id = "complaintForm", @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group" id="commentary">
                        @Html.LabelFor(model => model.Commentary, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Commentary, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group" id="result" style="display: none;">
                        <div class="col-md-12">
                            <p id="resultText"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            @Html.HiddenFor(model => model.PostId)
                            <input type="submit" id="complaintSubmit" class="btn btn-success" value="Denunciar" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.ActionLink("Listado de Publicaciones", "List", "Post", null, new { @id = "goBackBtn", @class = "btn btn-success", @style = "display: none;" })
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

DotW/DotW/Views/Post/_PostComplaint.cshtml
@model DotW.Models.PostComplaintViewModel

<div id="postComplaintModal" class="modal fade in" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content row">
            <div class="modal-header custom-modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 class="modal-title">Denunciar Publicación</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("PostComplaint", "Complaint", FormMethod.Post, new { @id = "postComplaintForm", @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group" id="postComplaintCommentary">
                        @Html.LabelFor(model => model.Commentary, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Commentary, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group" id="postComplaintResult" style="display: none;">
                        <div class="col-md-12">
                            <p id="postComplaintResultText"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            @Html.HiddenFor(model => model.PostId)
                            <input type="submit" id="postComplaintSubmit" class="btn btn-success" value="Denunciar" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.ActionLink("Listado de Publicaciones", "List", "Post", null, new { @id = "postGoBackBtn", @class = "btn btn-success", @style = "display: none;" })
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>